#!/usr/bin/env python3

import argparse
import isoform

parser = argparse.ArgumentParser(
	description='Isoform comparing program')
parser.add_argument('gff1', type=str, metavar='<file>',
	help='input gff file 1')
parser.add_argument('gff2', type=str, metavar='<file>',
	help='input gff file 2')
arg = parser.parse_args()

i1 = isoform.get_introns(arg.gff1)
i2 = isoform.get_introns(arg.gff2)

dist, details = isoform.expdiff(i1, i2)
print(dist)
for exon, p1, p2 in details:
	print(f'{exon[0]}\t{exon[1]}\t{p1:.6f}\t{p2:.6f}')
